name: travel_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  go_router: ^14.6.3
  provider: ^6.1.2
  image_picker: ^1.1.2
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  assets:
    - assets/images/
    - assets/images/offers/
    - assets/images/onboarding/
    - assets/images/places/
    - assets/icons/
  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: fonts/Urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: fonts/Urbanist/Urbanist-Black.ttf
          weight: 900

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700